stages:
    - deploy
deploy:
  stage: deploy
  image: node:latest
  script:
    - cd ecofresh/client
    - npm install
    - cd ../..
    - git subtree push --prefix ecofresh/client/ https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/group10-ecofresh.git main
    - echo "Deployed to heroku server"
  environment:
    name: production
    url: https://group10-ecofresh.herokuapp.com/
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
